name: poems
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  line_icons: ^0.2.0
  http: ^0.12.0+2
  shared_preferences: ^0.5.0
  firebase_admob: ^0.9.3+2
  admob_flutter: ^0.3.4
  flutter_native_admob: ^2.1.0
  dio: ^3.0.9
  smooth_star_rating: ^1.1.1
  share: ^0.6.4+3
  dynamic_theme: ^1.0.0
  sqflite: ^1.0.0
  path_provider: ^1.6.8
  cached_network_image: ^2.0.0
  image_picker_saver: ^0.3.0
  provider: ^3.2.0
  image_gallery_saver: ^1.5.0
  permission_handler: ^3.0.1
  network_to_file_image: ^2.0.0
  progress_dialog: ^1.1.0+1
  ads: ^1.7.3
  auto_size_text: ^2.1.0
  responsive_flutter: ^0.0.4
  flutter_screenutil: ^2.3.1
  save_in_gallery: ^0.1.3
  url_launcher: ^5.5.3
 # foreground_service: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg
    # - assets/logo.png
    # - assets/bg.jpg
    - assets/apps1.jpg
    - assets/apps2.jpg
    - assets/apps3.jpg
    - assets/splashscreen.jpg
    - assets/arrow_small.png
    - assets/categoryBack.png
    - assets/homeiconactive.png
    - assets/favactive.png
    - assets/topactive.png
    - assets/baricon1.png
    - assets/baricon2.png
    - assets/baricon3.png
    - assets/baricon4.png
    - assets/addImg.jpg
    - assets/friendPic.png
    - assets/frnds.png
    - assets/social1.png
    - assets/social2.png
    - assets/social3.png
    - assets/social4.png
    - assets/toplove.png
    - assets/topactive.png
    - assets/birthday.png
    - assets/megaphone.png
    - assets/popbg.png
    - assets/moon.png
    - assets/check.png
    - assets/poem_cat.txt
    - assets/top_poem.txt
    - assets/categorybg.jpg
    - assets/category.jpg
    - assets/topcategory.jpg
    - assets/favourite.jpg
    - assets/subcatpoem.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SpecialElite
      fonts:
        - asset: fonts/SpecialElite-Regular.ttf
    - family: GreatVibes
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf
    - family: CaveatB
      fonts:
        - asset: fonts/Caveat-Bold.ttf
    - family: SatisfyRegular
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
    - family: whitneymedium
      fonts:
        - asset: fonts/whitneymedium.ttf
    - family: whitneybold
      fonts:
        - asset: fonts/whitneybold.ttf
    - family: whitneybook
      fonts:
        - asset: fonts/whitneybook.ttf
    - family: whitneylight
      fonts:
        - asset: fonts/whitneylight.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
